---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  labels:
    purpose: developer-editions
  name: ibm-mariadb-dev
  namespace: developer-editions
  annotations:
    tillerVersion: 2.9.1
spec:
  channel: ibmcom/ibm-developer-edition-charts
  name: ibm-mariadb-dev
  #packageFilter:
  #  version: "1.0.0"
  placement:
    placementRef:
      name: dev-placementrule
      kind: PlacementRule
  packageOverrides:
  - packageName: ibm-mariadb-dev
    packageOverrides:
    - path: spec.values
      value: |
        # Additional values: https://github.com/IBM/charts/tree/master/stable/ibm-mariadb-dev
        password: mymariadb123
        name: maria-admin
        persistence:
          enabled: false
          useDynamicProvisioning: false
